e_shop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('products.urls')),
]

products/models.py
from django.contrib.auth.models import User
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=50)
    parent_category = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return f'{self.name}'


class Product(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    stock = models.IntegerField(default=0)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='static/product_images/', default='static/not_available.png')
    promoted = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.name}'


class Cart(models.Model):  # cosul user-ului
    STATUS_CHOICES = (('open', 'Open'), ('checked_out', 'Checked Out'), (
    'sent', 'Sent Item'))  # o tupla de tuple pentru dropdown. Primul parametru este valoarea din baza de date,
    # al doilea parametru este valoarea afisata utilizatorului.
    user = models.ForeignKey(User, on_delete=models.CASCADE)  # Clasa User este importata din Django
    status = models.CharField(max_length=15,
                              choices=STATUS_CHOICES)  # primind choices= acest CharField devine dropdown in Html.

    def __str__(self):
        return f'{self.status} cart of {self.user}'


class CartItem(models.Model):  # echivalentul unui produs in cos
    product = models.ForeignKey(Product, on_delete=models.CASCADE)  # are un produs
    quantity = models.IntegerField(default=1)  # are o cantitate
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)  # apartine unui Cart.

    def __str__(self):
        return f'{self.quantity} X {self.product} in {self.cart}'


class AboutUs(models.Model):
    name = models.CharField(max_length=50)
    position = models.CharField(max_length=250)
    personal_info = models.TextField()
    email = models.EmailField(default="nimic@chiarnimic.wow")

    def __str__(self):
        return f'{self.name}'


class ClientProfile(models.Model):
    phone_number = models.CharField(max_length=20)
    shipping_adress = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return f'{self.user.username} {self.phone_number}'

templates/pages/about_us.html
{% extends 'base.html' %}
{% block body %}
    <style>
        .body_class {
            background-color: #ccaa11;
            font-family: Arial, Helvetica, sans-serif;
            margin: 0;
        }

        .html_class {
            box-sizing: border-box;
        }
        

        .column {
            float: left;
            width: 33.3%;
            margin-bottom: 16px;
            padding: 0 8px;
        }

        .card {
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
            margin: 8px;
        }

        .about-section {
            padding: 50px;
            text-align: center;
            background-color: #474e5d;
            color: white;
        }

        .container {
            padding: 0 16px;
        }

        .container::after, .row::after {
            content: "";
            clear: both;
            display: table;
        }

        .title {
            color: grey;
        }

        .button {
            border: none;
            outline: 0;
            display: inline-block;
            padding: 8px;
            color: white;
            background-color: #000;
            text-align: center;
            cursor: pointer;
            width: 100%;
        }

        .button:hover {
            background-color: #555;
        }

        @media screen and (max-width: 650px) {
            .column {
                width: 100%;
                display: block;
            }
        }

    </style>
    <div class="about-section">
        <h1>About Us Page</h1>
        <p>Some text about who we are and what we do.</p>
        <p>Resize the browser window to see that this page is responsive by the way.</p>
    </div>

    <h2 style="text-align:center">Our Team</h2>
    <div class="row">
        <div class="column">
            <div class="card">
                <img src="/w3images/team1.jpg" alt="Jane" style="width:100%">
                <div class="container">
                    <h2>Jane Doe</h2>
                    <p class="title">CEO & Founder</p>
                    <p>Some text that describes me lorem ipsum ipsum lorem.</p>
                    <p>jane@example.com</p>
                    <p>
                        <button class="button">Contact</button>
                    </p>
                </div>
            </div>
        </div>

        <div class="column">
            <div class="card">
                <img src="/w3images/team2.jpg" alt="Mike" style="width:100%">
                <div class="container">
                    <h2>Mike Ross</h2>
                    <p class="title">Art Director</p>
                    <p>Some text that describes me lorem ipsum ipsum lorem.</p>
                    <p>mike@example.com</p>
                    <p>
                        <button class="button">Contact</button>
                    </p>
                </div>
            </div>
        </div>

        <div class="column">
            <div class="card">
                <img src="/w3images/team3.jpg" alt="John" style="width:100%">
                <div class="container">
                    <h2>John Doe</h2>
                    <p class="title">Designer</p>
                    <p>Some text that describes me lorem ipsum ipsum lorem.</p>
                    <p>john@example.com</p>
                    <p>
                        <button class="button">Contact</button>
                    </p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/pages/admin_page.html
{% extends 'base.html' %}

{% block title %} Admin page {% endblock %}
{% block body %}

    {% if perms.products.view_category %}
        <a class="btn btn-primary" href="{% url 'category_all_view' %}" role="button">List Categories</a>
    {% endif %}

    {% if perms.products.add_category %}
        <a class="btn btn-success" href="{% url 'category_create' %}" role="button">Create Category</a>
    {% endif %}

    {% if perms.products.view_product %}
        <a class="btn btn-outline-primary" href="{% url 'product_all_view' %}" role="button">List Products</a>
    {% endif %}

    {% if perms.products.add_product %}
        <a class="btn btn-outline-success" href="{% url 'product_create' %}" role="button">Create Product</a>
    {% endif %}
    {% if request.user.is_staff %}
        <a class="btn btn-dark" href="{% url 'admin_page' %}" role="button">Home admin</a>
    {% endif %}
    {#    <a class="btn btn-primary" href="{% url 'article_update' %}" role="button">Update article</a>#}
    {#    <a class="btn btn-primary" href="{% url 'article_delete' %}" role="button">Delete article</a>#}

    {% block admin_content %}{% endblock %}
{% endblock %}

templates/pages/category_all_view.html
{% extends 'pages/admin_page.html' %}

{% block title %} All categories view {% endblock %}
{% block admin_content %}
    {% for category in categories %}
        {% if not category.parent_category %}
            <div class="card bg-dark text-white mb-1" style="max-width: 20rem;">
                <div class="card-header fw-bold">{{ category.name }}</div>
                <div class="card-body">
                    {% if perms.products.change_category %}
                        <a class="btn btn-primary btn-sm" href="{% url 'category_update' category.id %}" role="button">Update</a>
                    {% endif %}
                    {% if perms.products.add_category %}
                        <a class="btn btn-success btn-sm" href="{% url 'category_create' %}" role="button">Create
                            SubCategory</a>
                    {% endif %}
                    {% if perms.products.delete_category %}
                        <a class="btn btn-danger btn-sm" href="{% url 'category_delete' category.id %}"
                           role="button">Delete</a>
                    {% endif %}
                </div>
            </div>
            {% for subcateg in categories %}
                {% if subcateg.parent_category == category %}
                    <div class="card border-primary border-2 mb-1" style="max-width: 20rem;">
                        <div class="card-header fw-bold">{{ subcateg.name }}</div>
                        <div class="card-body">
                            {% if perms.products.change_category %}
                                <a class="btn btn-primary btn-sm" href="{% url 'category_update' subcateg.id %}"
                                   role="button">Update</a>
                            {% endif %}
                            {% if perms.products.delete_category %}
                                <a class="btn btn-danger btn-sm" href="{% url 'category_delete' subcateg.id %}"
                                   role="button">Delete</a>
                            {% endif %}
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}
    {% endfor %}
{% endblock %}

templates/pages/category_create.html
{% extends 'pages/admin_page.html' %}

{% block title %} Create category/subcategory {% endblock %}
{% block admin_content %}
    <form method="post" enctype="multipart/form-data">
{#   enctype="multipart/form-data" - ne trebuie ca sa mearga upload-ul de fisiere (in cazul de fata imaginea de articol) #}
        {#    cross-site referecing attac protection#}
        {% csrf_token %}
        {#        orice formular are metode. as_p genereaza paragrafe cu fiecare field #}
        {#        mai exista as_ul, as_ol, etc #}
        {{ form.as_p }}
        <button type="submit">Create category</button>
    </form>

{% endblock %}

templates/pages/category_delete.html
{% extends 'pages/admin_page.html' %}

{% block title %} Delete category {% endblock %}
{% block admin_content %}
    <p>Are you sure you want to delete {{ category.name }}</p>
    <form method="post">
        {#    cross-site referecing attac protection#}
        {% csrf_token %}
        {#        orice formular are metode. as_p genereaza paragrafe cu fiecare field #}
        {#        mai exista as_ul, as_ol, etc #}
        <button type="submit">Delete category</button>
    </form>

{% endblock %}

templates/pages/category_details.html
{% extends 'base.html' %}

{% block body %}
    {% include 'partials/title_and_products_block.html' with title=category.name %}

{% endblock %}

templates/pages/homepage.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
    {% include 'partials/title_and_products_block.html' with title='Last products' products=last_products %}
    <div class="container-xl">
        <h3>Carusel</h3>
        <div class="row" style="height: 500px; width: 500px">
            <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-inner">
                    {% for carusel_product in carusel_products %}
                        <div class="carousel-item {% if forloop.first == 1 %}active{% endif %}" data-bs-interval="5000">
                            <img src="{{ carusel_product.image.url }}" class="d-block w-100" alt="...">
                        </div>
                    {% empty %}
                        <div class="carousel-item active" data-bs-interval="5000">
                            <img src="{% static 'not_available.png' %}" class="d-block w-100" alt="...">
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/pages/open_cart.html
<!--Section: Block Content-->
{% extends 'base.html' %}

{% block body %}
    <div class="container-xl">
        {% for cart_item_with_total in open_cart_items_with_totals %}
            <div class="row">
                <div class="card border-primary mb-1" style="max-width: 50rem;">
                    <div class="card-header"><h5><b>{{ cart_item_with_total.cart_item.product.name }}</b></h5></div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-3">
                                <img src="{{ cart_item_with_total.cart_item.product.image.url }}" class="card-img "
                                     alt="{{ cart_item_with_total.cart_item.product.name }}">
                            </div>
                            <div class="col-3">
                                <p><b>Pret: {{ cart_item_with_total.cart_item.product.price }} Lei</b></p>

                            </div>
                            <div class="col-3">
                                <p><b>Buc: {{ cart_item_with_total.cart_item.quantity }}</b></p>

                            </div>
                            <div class="col-3">
                                <p><b>Total: {{ cart_item_with_total.total}} Lei</b></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
        <div class="row">
            <div class="card border-primary mb-1" style="max-width: 50rem;">
                <div class="card-header">
                    <div class="row">
                        <div class="col-9">
                        </div>
                        <div class="col-3">
                            <p><b>Total comanda: {{ total_cart }} Lei</b></p>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
{% endblock %}
<!--Section: Block Content-->

{#<div class="card col-xl-3 col-lg-4 col-md-6 col-sm-12">#}
{#                <img src="{{ product.image.url }}" class="card-img-top" alt="{{ product.name }}">#}
{#                <div class="card-body">#}
{#                    <h5 class="card-title">{{ product.name }}</h5>#}
{#                    <p class="card-text">{{ product.price }} lei</p>#}
{#                    <a href="#" class="btn btn-primary m-1">Add to cart</a>#}
{#                    <a href="{% url 'product_details' product.id %}" class="btn btn-secondary m-1">Product details</a>#}
{#                </div>#}
{#            </div>#}

templates/pages/product_create.html
{% extends 'pages/admin_page.html' %}

{% block title %} Create product {% endblock %}
{% block admin_content %}
    <form method="post" enctype="multipart/form-data">
{#   enctype="multipart/form-data" - ne trebuie ca sa mearga upload-ul de fisiere (in cazul de fata imaginea de articol) #}
        {#    cross-site referecing attac protection#}
        {% csrf_token %}
        {#        orice formular are metode. as_p genereaza paragrafe cu fiecare field #}
        {#        mai exista as_ul, as_ol, etc #}
        {{ form.as_p }}
        <button type="submit">Create product</button>
    </form>

{% endblock %}

templates/pages/product_delete.html
{% extends 'pages/admin_page.html' %}

{% block title %} Delete product {% endblock %}
{% block admin_content %}
    <p>Are you sure you want to delete {{ product.name }}</p>
    <form method="post">
        {#    cross-site referecing attac protection#}
        {% csrf_token %}
        {#        orice formular are metode. as_p genereaza paragrafe cu fiecare field #}
        {#        mai exista as_ul, as_ol, etc #}
        <button type="submit">Delete product</button>
    </form>

{% endblock %}

templates/pages/product_details.html
{% extends 'base.html' %}

{% block body %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css">
    <style>
        body {
            background-color: #ecedee
        }

        .card {
            border: none;
            overflow: hidden
        }

        .thumbnail_images ul {
            list-style: none;
            justify-content: center;
            display: flex;
            align-items: center;
            margin-top: 10px
        }

        .thumbnail_images ul li {
            margin: 5px;
            padding: 10px;
            border: 2px solid #eee;
            cursor: pointer;
            transition: all 0.5s
        }

        .thumbnail_images ul li:hover {
            border: 2px solid #000
        }

        .main_image {
            display: flex;
            justify-content: center;
            align-items: center;
            border-bottom: 1px solid #eee;
            height: 400px;
            width: 100%;
            overflow: hidden
        }

        .heart {
            height: 29px;
            width: 29px;
            background-color: #eaeaea;
            border-radius: 50%;
            display: flex;
            justify-content: center;
            align-items: center
        }

        .content p {
            font-size: 12px
        }

        .ratings span {
            font-size: 14px;
            margin-left: 12px
        }

        .colors {
            margin-top: 5px
        }

        .colors ul {
            list-style: none;
            display: flex;
            padding-left: 0px
        }

        .colors ul li {
            height: 20px;
            width: 20px;
            display: flex;
            border-radius: 50%;
            margin-right: 10px;
            cursor: pointer
        }

        .colors ul li:nth-child(1) {
            background-color: #6c704d
        }

        .colors ul li:nth-child(2) {
            background-color: #96918b
        }

        .colors ul li:nth-child(3) {
            background-color: #68778e
        }

        .colors ul li:nth-child(4) {
            background-color: #263f55
        }

        .colors ul li:nth-child(5) {
            background-color: black
        }

        .right-side {
            position: relative
        }

        .search-option {
            position: absolute;
            background-color: #000;
            overflow: hidden;
            align-items: center;
            color: #fff;
            width: 200px;
            height: 200px;
            border-radius: 49% 51% 50% 50% / 68% 69% 31% 32%;
            left: 30%;
            bottom: -250px;
            transition: all 0.5s;
            cursor: pointer
        }

        .search-option .first-search {
            position: absolute;
            top: 20px;
            left: 90px;
            font-size: 20px;
            opacity: 1000
        }

        .search-option .inputs {
            opacity: 0;
            transition: all 0.5s ease;
            transition-delay: 0.5s;
            position: relative
        }

        .search-option .inputs input {
            position: absolute;
            top: 200px;
            left: 30px;
            padding-left: 20px;
            background-color: transparent;
            width: 300px;
            border: none;
            color: #fff;
            border-bottom: 1px solid #eee;
            transition: all 0.5s;
            z-index: 10
        }

        .search-option .inputs input:focus {
            box-shadow: none;
            outline: none;
            z-index: 10
        }

        .search-option:hover {
            border-radius: 0px;
            width: 100%;
            left: 0px
        }

        .search-option:hover .inputs {
            opacity: 1
        }

        .search-option:hover .first-search {
            left: 27px;
            top: 25px;
            font-size: 15px
        }

        .search-option:hover .inputs input {
            top: 20px
        }

        .search-option .share {
            position: absolute;
            right: 20px;
            top: 22px
        }

        .buttons .btn {
            height: 50px;
            width: 150px;
            border-radius: 0px !important
        }
    </style>
    <script>
        function changeImage(element) {

            var main_prodcut_image = document.getElementById('main_product_image');
            main_prodcut_image.src = element.src;


        }
    </script>
    <div class="container mt-5 mb-5">
        <div class="card">
            <div class="row g-0">
                <div class="col-md-6 border-end">
                    <div class="d-flex flex-column justify-content-center">
                        <div class="main_image"><img src="https://i.imgur.com/TAzli1U.jpg" id="main_product_image"
                                                     width="350"></div>
                        <div class="thumbnail_images">
                            <ul id="thumbnail">
                                <li><img onclick="changeImage(this)" src="https://i.imgur.com/TAzli1U.jpg" width="70">
                                </li>
                                <li><img onclick="changeImage(this)" src="https://i.imgur.com/w6kEctd.jpg" width="70">
                                </li>
                                <li><img onclick="changeImage(this)" src="https://i.imgur.com/L7hFD8X.jpg" width="70">
                                </li>
                                <li><img onclick="changeImage(this)" src="https://i.imgur.com/6ZufmNS.jpg" width="70">
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="p-3 right-side">
                        <div class="d-flex justify-content-between align-items-center">
                            <h3>{{ product.name }}</h3> <span class="heart"><i class='bx bx-heart'></i></span>
                        </div>
                        <div class="mt-2 pr-3 content">
                            <p>{{ product.description}}</p>
                        </div>
                        <h3>{{ product.price }} lei</h3>
                        <div class="ratings d-flex flex-row align-items-center">
                            <div class="d-flex flex-row"><i class='bx bxs-star'></i> <i class='bx bxs-star'></i> <i
                                    class='bx bxs-star'></i> <i class='bx bxs-star'></i> <i class='bx bx-star'></i>
                            </div>
                            <span>441 reviews</span>
                        </div>
{#                        <div class="mt-5"><span class="fw-bold">Color</span>#}
{#                            <div class="colors">#}
{#                                <ul id="marker">#}
{#                                    <li id="marker-1"></li>#}
{#                                    <li id="marker-2"></li>#}
{#                                    <li id="marker-3"></li>#}
{#                                    <li id="marker-4"></li>#}
{#                                    <li id="marker-5"></li>#}
{#                                </ul>#}
{#                            </div>#}
{#                        </div>#}
                        <div class="buttons d-flex flex-row mt-5 gap-3">
                            <button class="btn btn-outline-dark">Add to cart</button>
{#                            <button class="btn btn-dark">Add to Basket</button>#}
                        </div>
{#                        <div class="search-option"><i class='bx bx-search-alt-2 first-search'></i>#}
{#                            <div class="inputs"><input type="text" name=""></div>#}
{#                            <i class='bx bx-share-alt share'></i>#}
{#                        </div>#}
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/pages/product_update.html
{% extends 'pages/admin_page.html' %}

{% block title %} Update Product {% endblock %}
{% block admin_content %}
    <form method="post" enctype="multipart/form-data">
{#   enctype="multipart/form-data" - ne trebuie ca sa mearga upload-ul de fisiere (in cazul de fata imaginea de articol) #}
        {#    cross-site referecing attac protection#}
        {% csrf_token %}
        {#        orice formular are metode. as_p genereaza paragrafe cu fiecare field #}
        {#        mai exista as_ul, as_ol, etc #}
        {{ form.as_p }}
        <button type="submit">Update product</button>
    </form>

{% endblock %}

templates/pages/register.html
{% extends 'base.html' %}
{% block body %}
    <form method="post">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ client_profile_form.as_p }}
        <button type="submit">Register</button>
    </form>
{% endblock %}

templates/pages/search_results.html
{% extends 'base.html' %}

{% block title %} Search results {% endblock %}
{% block body %}
{% include 'partials/title_and_products_block.html' with title='Search results' %}


{% endblock %}